services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-${PREFIX}
    volumes:
      - ./www:/var/www/html
    ports:
      - "${PHP_PORT}:80"
    depends_on:
      - db
    restart: always
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    command: >
      bash -c "chown -R www-data:www-data /var/www/html &&
               chmod -R 777 /var/www/html &&
               apache2-foreground"  

  db:
    image: mysql:5.7
    container_name: mysql-${PREFIX}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data_${PREFIX}:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-${PREFIX}
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: 128M
    ports:
      - "${PHPMYADMIN_PORT}:80"

volumes:
  db_data_prestashop9:
