<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCUWOMe9\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCUWOMe9/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerCUWOMe9.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerCUWOMe9\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerCUWOMe9\AdminKernelProdContainer([
    'container.build_hash' => 'CUWOMe9',
    'container.build_id' => 'bfa8b2fc',
    'container.build_time' => 1757509313,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCUWOMe9');
